name: Release Build

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Version bump type: patch, minor, major'
        required: true
        default: 'patch'
permissions:
  contents: write

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Bump version
        id: bump
        run: |
          bump_type="${{ github.event.inputs.bump_type }}"
          echo "Bumping version: $bump_type"
          npm version $bump_type --no-git-tag-version
          version=$(node -p "require('./package.json').version")
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Create tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "chore: release v${{ steps.bump.outputs.version }}"
          git tag v${{ steps.bump.outputs.version }}
          git push origin HEAD --tags

      - name: Build binaries
        run: npm run build

      - name: Generate SHA256SUMS and manifest.json
        run: node .github/scripts/gen-manifest.js

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.bump.outputs.version }}
          name: Release v${{ steps.bump.outputs.version }}
          files: |
            dist/qidian-decryptor-*
            dist/SHA256SUMS
            dist/manifest.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
